import { Images } from "@config";
import * as Utils from "@utils";
import Axios from "axios"
export const getSetting = async ({ params }) => {
  await Utils.delay(1000);
  const location = await Axios.get('http://semmsar.com/wp-json/_rtcl/_rtcl_location');
  const location_array = location.data


  const recent = await Axios.get('http://semmsar.com/wp-json/wp/v2/rtcl_location?_embed');
  const recent_post = recent.data
 

  // recent_post.forEach(element => {
    
  // });




  const cat = await Axios.get('http://semmsar.com/wp-json/wp/v2/rtcl_category?_embed');
  const category_array = cat.data

  return {
    success: true,
    data: {
      categories: category_array,
      features: [
        {
          term_id: 12,
          name: "Credit Cards",
          slug: "credit-cards",
          term_group: 0,
          term_taxonomy_id: 12,
          taxonomy: "listar_feature",
          description: "",
          parent: 0,
          count: 65,
          filter: "raw",
          featured_image: "",
          icon: "far fa-credit-card",
          color: "#a569bd",
        },
        {
          term_id: 13,
          name: "Delivery",
          slug: "delivery",
          term_group: 0,
          term_taxonomy_id: 13,
          taxonomy: "listar_feature",
          description: "",
          parent: 0,
          count: 148,
          filter: "raw",
          featured_image: "",
          icon: "fas fa-bicycle",
          color: "#e5634d",
        },
        {
          term_id: 15,
          name: "Dogs Allowed",
          slug: "dogs-allowed",
          term_group: 0,
          term_taxonomy_id: 15,
          taxonomy: "listar_feature",
          description: "",
          parent: 0,
          count: 218,
          filter: "raw",
          featured_image: "",
          icon: "fas fa-paw",
          color: "#e5634d",
        },
        {
          term_id: 16,
          name: "Free Parking",
          slug: "free-parking",
          term_group: 0,
          term_taxonomy_id: 16,
          taxonomy: "listar_feature",
          description: "",
          parent: 0,
          count: 301,
          filter: "raw",
          featured_image: "",
          icon: "fas fa-parking",
          color: "#e5634d",
        },
        {
          term_id: 17,
          name: "Free Wifi",
          slug: "free-wifi",
          term_group: 0,
          term_taxonomy_id: 17,
          taxonomy: "listar_feature",
          description: "",
          parent: 0,
          count: 375,
          filter: "raw",
          featured_image: "",
          icon: "fas fa-wifi",
          color: "#e5634d",
        },
        {
          term_id: 14,
          name: "Good for Kids",
          slug: "good-for-kids",
          term_group: 0,
          term_taxonomy_id: 14,
          taxonomy: "listar_feature",
          description: "",
          parent: 0,
          count: 441,
          filter: "raw",
          featured_image: "",
          icon: "fas fa-users",
          color: "#e5634d",
        },
        {
          term_id: 70,
          name: "Karaoke",
          slug: "karaoke",
          term_group: 0,
          term_taxonomy_id: 70,
          taxonomy: "listar_feature",
          description: "",
          parent: 0,
          count: 508,
          filter: "raw",
          featured_image: "",
          icon: "fas fa-microphone",
          color: "#5d6d7e",
        },
        {
          term_id: 69,
          name: "Outdoor Seating",
          slug: "outdoor-seating",
          term_group: 0,
          term_taxonomy_id: 69,
          taxonomy: "listar_feature",
          description: "",
          parent: 0,
          count: 560,
          filter: "raw",
          featured_image: "",
          icon: "fas fa-cloud",
          color: "#3c5a99",
        },
        {
          term_id: 11,
          name: "Reservations",
          slug: "reservations",
          term_group: 0,
          term_taxonomy_id: 11,
          taxonomy: "listar_feature",
          description: "",
          parent: 0,
          count: 614,
          filter: "raw",
          featured_image: "",
          icon: "fas fa-phone",
          color: "#e5634d",
        },
        {
          term_id: 19,
          name: "Shower",
          slug: "shower",
          term_group: 0,
          term_taxonomy_id: 19,
          taxonomy: "listar_feature",
          description: "",
          parent: 0,
          count: 676,
          filter: "raw",
          featured_image: "",
          icon: "fas fa-shower",
          color: "#e5634d",
        },
        {
          term_id: 18,
          name: "Smoking Allowed",
          slug: "smoking-allowed",
          term_group: 0,
          term_taxonomy_id: 18,
          taxonomy: "listar_feature",
          description: "",
          parent: 0,
          count: 700,
          filter: "raw",
          featured_image: "",
          icon: "fas fa-fire",
          color: "#e5634d",
        },
        {
          term_id: 68,
          name: "Takes Reservations",
          slug: "takes-reservations",
          term_group: 0,
          term_taxonomy_id: 68,
          taxonomy: "listar_feature",
          description: "",
          parent: 0,
          count: 706,
          filter: "raw",
          featured_image: "",
          icon: "fas fa-phone",
          color: "#5dade2",
        },
      ],
      locations:location_array,
      settings: {
        per_page: 20,
        color_option: [
          "#E5634D",
          "#5DADE2",
          "#A569BD",
          "#58D68D",
          "#FDC60A",
          "#3C5A99",
          "#5D6D7E",
        ],
        unit_price: "USD",
        price_min: 9,
        price_max: 99,
        time_min: "09:00",
        time_max: "18:00",
        list_mode: "list",
      },
      place_sort_option: [
        {
          title: "Lastest Post",
          field: "post_date",
          lang_key: "post_date_desc",
          value: "DESC",
        },
        {
          title: "Oldest Post",
          field: "post_date",
          lang_key: "post_date_asc",
          value: "ASC",
        },
        {
          title: "Most Views",
          field: "comment_count",
          lang_key: "comment_count_desc",
          value: "DESC",
        },
      ],
    },
  };
};
